name: socialservices
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  graphql_flutter: ^5.1.2
  image_picker: ^1.0.4
  intl: ^0.18.1
  shared_preferences: ^2.2.1
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - images/avatar.png

  fonts:
    - family: Outfit
      fonts:
        - asset: fonts/Outfit-VariableFont_wght.ttf

